ABCMobile/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('portal.urls', namespace="portal")),
    #url(r'^', include('api.urls')),
    url(r'^api/', include('api.urls')),
    #url(r'^', include('api.urls',    namespace="api")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.conf.urls import url, include
from .views import *
from portal.views import *
from django.contrib.admin import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^portal/', portal,    name='portal'),
    url(r'^login/',  do_login,  name='login'),
    url(r'^logout/', do_logout, name='logout'),

    url(r'^mobile/', mobile, name='mobile'),

    url(r'^responsavel_usuario/', responsavel_usuario, name="responsavel_usuario"),
    url(r'^usuario_new/', usuario_new, name="usuario_new"),
    url(r'^usuario_edit/(?P<pk>[0-9]+)', usuario_edit, name="usuario_edit"),

    url(r'^instituicao/', instituicao, name='instituicao'),
    url(r'^instituicao_new/', instituicao_new, name="instituicao_new"),
    url(r'^instituicao_edit/(?P<pk>[0-9]+)', instituicao_edit, name="instituicao_edit"),

    url(r'^periodoletivo/', periodoletivo, name='periodoletivo'),
    url(r'^periodoletivo_new/', periodoletivo_new, name="periodoletivo_new"),
    url(r'^periodoletivo_edit/(?P<pk>[0-9]+)', periodoletivo_edit, name="periodoletivo_edit"),

    # url(r'^turma/', turma, name='turma'),
    # url(r'^turma_new/', turma_new, name="turma_new"),
    # url(r'^turma_edit/(?P<pk>[0-9]+)', turma_edit, name="turma_edit"),
    # #
    # url(r'^disciplina/', disciplina, name='disciplina'),
    # url(r'^disciplina_new/', disciplina_new, name="disciplina_new"),
    # url(r'^disciplina_edit/(?P<pk>[0-9]+)', disciplina_edit, name="disciplina_edit"),
    #
    # url(r'^turmadisciplina/', turmadisciplina, name='turmadisciplina'),
    # url(r'^form_turmadisciplina/(?P<pk>[0-9]+)', form_turmadisciplina, name='form_turmadisciplina'),

    url(r'^aluno/', aluno, name='aluno'),
    url(r'^form_aluno/(?P<pk>[0-9]+)', form_aluno, name='form_aluno'),
    url(r'^graficos/(?P<pk>[0-9]+)', graficos, name='grafico'),

    #    url(r'^importar_csv/', importar_csv, name='importar_csv'),

    url(r'^professor/', professor, name='professor'),
    url(r'^form_professor/(?P<pk>[0-9]+)', form_professor, name='form_professor'),

    # url(r'^financeiro/(?P<pk>[0-9]+)', financeiro, name='financeiro'),

    url(r'^form_boletim/(?P<pk>[0-9]+)', form_boletim, name='form_boletim'),

    url(r'^responsavel/', responsavel, name='responsavel'),
    url(r'^form_responsavel/(?P<pk>[0-9]+)', form_responsavel, name='form_responsavel'),
    #url(r'^edit_responsavel/(?P<pk>[0-9]+)', edit_responsavel, name='edit_responsavel'),

    url(r'^perfil/', perfil, name='perfil'),
    url(r'^upload/', upload, name='upload'),
    url(r'^administracao/', administracao,   name='administracao'),

    #url(r'^importacao_csv/(?P<pk>[0-9]+)', importacao_csv, name='importacao_csv'),
    url(r'^importacao_excel/(?P<pk>[0-9]+)', importacao_excel, name='importacao_excel'),
    url(r'^excluir_dados_importacao/(?P<pk>[0-9]+)', excluir_dados_importacao, name='excluir_dados_importacao'),
    # url(r'^importacao_excel/(?P<pk>[0-9]+)/(?P<str>\d{2}/$)', importacao_excel, name='importacao_excel'),
    # (r'^articles/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d+)/$', 'news.views.article_detail'),
    url(r'^upload_csv/', upload_csv, name='upload_csv'),

    # url(r'^importacao_excel/', importacao_excel, name='importacao_excel'),

    url(r'^mensagem/', mensagem, name='mensagem'),
    url(r'^mensagem_new/', mensagem_new, name='mensagem_new'),
    url(r'^mensagem_edit/(?P<pk>[0-9]+)', mensagem_edit, name='mensagem_edit'),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('sistema.urls', namespace="sistema")),
    url(r'^',include('api.urls')),
    #url(r'^user/', include('users.urls', namespace="users")),
]

portal/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.shortcuts import render, redirect,get_object_or_404, HttpResponseRedirect, render_to_response # funcoes de renderizacao dos templates
from django.contrib.auth import authenticate,login,logout
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import datetime

from portal.models import *
from portal.forms import *

from django.db.models import Sum, Avg, FloatField, Count, F, Max, Min

from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.core.files.uploadedfile import InMemoryUploadedFile


from django.utils.formats import localize

import json
import decimal

from django.conf import settings

import csv
import codecs
import xlrd

import sys
# reload(sys)
import importlib
importlib.reload(sys)
# sys.setdefaultencoding('utf8')
import os


from datetime import datetime
# Create your views here.

def getPeriodoLetivo():

    periodoletivo = PeriodoLetivo.objects.filter(dtfinal__isnull=True)

    return periodoletivo


def mobile(request):

    return redirect('mobile:index')

@login_required
def portal(request):

   #Instituicao
   instituicao = Instituicao.objects.all()

   if instituicao:

       # Alunos

       if request.user.is_superuser:
           alunos = Aluno.objects.all()
       else: ######### REVER ESTA SITUACAO
           alunos = Aluno.objects.filter(usuario_id=request.user.pk)
           #alunos = Aluno.objects.all()



       #Total Alunos
       totAlunos = alunos.count()

       professores = Professor.objects.all()

       # Total Professor
       totProfessores = professores.count()

       # Total Responsavel
       #responsavel = User.objects.all()
       responsavel = User.objects.filter(is_superuser=False)
       totResponsavel = responsavel.count()

       # Pagtos Confirmados
    #   totTitulosPagos = Financeiro.objects.filter(dtbaixa__isnull= False).aggregate(total=Sum('vlr_titulo'))
       totTitulosPagos = Financeiro.objects.all().exclude(dtbaixa= 'NULL')

       # Pagtos Pendentes
    #   totTitulosAbertos = Financeiro.objects.filter(dtbaixa__isnull= True).aggregate(total=Sum('vlr_titulo'))
       totTitulosAbertos = Financeiro.objects.filter(dtbaixa = 'NULL')

       #Mensagem
       totMensagem = Mensagem.objects.all()

       return render(request,'index.html',{'instituicao': instituicao,
                                           'alunos': alunos,
                                           'professores': professores,
                                           'totAlunos': totAlunos,
                                           'totProfessor': totProfessores,
                                           'totResponsavel': totResponsavel,
                                           'totTitulosPagos': totTitulosPagos.count(),
                                           'totTitulosAbertos':totTitulosAbertos.count(),
                                           'totMensagem': totMensagem

                                           })
   # else:
   #
   #     #return redirect('/instituicao_new/')
   #     return redirect('/instituicao_edit/')

def mensagem(request, template="mensagem.html"):

    # usuario = User.objects.filter(pk=request.user.pk)
    # print("Usuario", request.user.pk)
    mensagem = Mensagem.objects.all()

    return render (request,template)

def mensagem_new(request,template='form_mensagem.html'):

    mensagem = Mensagem.objects.all()

    if request.method == "POST":
        form = MensagemForm(request.POST, request.FILES or None )

        if form.is_valid():

            form.save()


        # titulo = request.POST['titulo']
        # dtmensagem = request.POST['dtmensagem']
        # descricao = request.POST['descricao']
        # stmensagem = 0
        # #usuario_id = request.user.pk
        #
        # mensagem = Mensagem.objects.create(titulo=titulo,
        #                                    #dtmensagem=dtmensagem,
        #                                    dtmensagem= datetime.strptime(dtmensagem, '%d/%m/%Y').strftime('%Y-%m-%d'),
        #                                    stmensagem = stmensagem,
        #                                    descricao= descricao,usuario_id=request.user.pk)
        #
        # mensagem.save()
        messages.success(request, " Operação Realizada com Sucesso ! ")
        return redirect('mensagem.html')
    else:
        form = MensagemForm(request.POST or None)

    return render(request,template,{'form':form})

def mensagem_edit(request,pk,template_name='form_mensagem.html'):

    mensagem = get_object_or_404(Mensagem, pk=pk)

    if request.method == "POST":
        form = MensagemForm(request.POST, request.FILES, instance=mensagem)
        if form.is_valid():
            mensagem = form.save()
            messages.success(request, " Operação Realizada com Sucesso ! ")
        return render(request, template_name, {'form': form})
    else:
        form = MensagemForm(instance=mensagem)
    return render(request, template_name, {'form': form})

def administracao(request):

    if request.user.is_superuser:
        return redirect('/admin/')
    else:
        return redirect('/portal/')

def perfil(request):

    if request.user.is_superuser:
        #return redirect('/admin/auth/user/')
        return redirect('/admin/auth/user/')
    else:
        return redirect('/portal/')

def upload(request):

    if request.user.is_superuser:
        return redirect ('/admin/portal/importacaoxls/')
    else:
        return redirect('/portal/')


# def set_imagem(usuario):
#
#     #imagem_usuario = ImagemUsuarios.objects.all().filter(usuarios=usuario)
#     imagem_usuario = ImagemUsuarios.objects.all().filter(usuarios=usuario)
#
#     return imagem_usuario

def do_login(request, *args, **kwargs):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #if user.is_superuser:
                if not user.first_name:
                    return  redirect('/admin/auth/user/%s/change/' % str(request.user.pk))
                else:
                    # if user.is_superuser:
                    #     return redirect('/portal/')
                    return redirect('/portal/')
                # else:
                #     return redirect('mobile:index')

    return render(request, 'login.html')

def do_logout(request):
    logout(request)
    return redirect('/login/')

@login_required()
def inbox(request,template='inbox.html'):

    return render(request,template,{'mensagem': 'Mensagem'})


def responsavel_usuario (request,template_name="usuario.html"):

    #responsavel = Responsavel.objects.all()
    usuario = User.objects.all()

    return render(request,template_name,{'usuario':usuario})

    # for reg in responsavel:
    #
    #     username = reg.cpf
    #     email =    reg.email
    #     password = reg.cpf
    #     first_name = reg.nome
    # #    last_name = request.POST['last_name']
    #     imagem = reg.imagem
    #
    #     responsavel = reg.pk
    #
    #     usuario = User.objects.create_user(username=username, email=email, password=password, first_name=first_name,
    #                                        imagem=imagem,responsavel_id=responsavel )
    #     usuario.save()
    #
    #     # reg.usuario = request.user.pk
    #     # reg.save()
    #
    # messages.success(request, " Usuários x Responsável Criado com Sucesso ! ")
    # return redirect('/portal/')

def usuario_new(request, template="form_usuario.html"):

    if request.method =="POST":

        #form = UserForm(request.POST, request.FILES or None)

        username =  request.POST['username']
        email    =  request.POST['email']
        password =   request.POST['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        imagem = request.FILES['imagem']

        usuario = User.objects.create_superuser(username=username,email=email,password=password,first_name=first_name,
                                                last_name=last_name, imagem=imagem)
        usuario.save()
        messages.success(request, " Operação Realizada com Sucesso ! ")
        return redirect('/portal/')
    else:
        form = UserForm(request.POST, request.FILES or None)

    return render(request,template,{'form':form})

def usuario_edit(request, pk, template="form_usuario.html"):

    usuario = User.objects.all().filter(pk=pk)

    if not (usuario):

        pass

        # responsavel = Responsavel.objects.all()
        #
        # for reg in responsavel:
        #
        #     #usu = User.objects.filter(username=reg.cpf)
        #
        #     if not (User.objects.filter(username=reg.cpf)):
        #
        #         username = reg.cpf
        #         #username = reg.email
        #         email =    reg.email
        #         password = reg.cpf
        #         first_name = reg.nome
        #         #imagem = reg.imagem
        #         reg_id = reg.pk
        #         usuario = User.objects.create_user(username=username, email=email, password=password, first_name=first_name )
        #         usuario.save()
        #         messages.success(request, " Usuários x Responsável Criado com Sucesso ! ")


        #return redirect('/responsavel_usuario/')
    else:

        usuario = get_object_or_404(User, pk=pk)

        if request.method == "POST":
            form = UserForm(request.POST, request.FILES, instance=usuario)
            if form.is_valid():
                usuario = form.save()
                messages.success(request, " Operação Realizada com Sucesso ! ")

portal/templates/boletim.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>Boletim Acadêmico <small></small></h2>
			<ul class="nav navbar-right panel_toolbox">
				<li><a href="#"><i class="fa fa-chevron-up"></i></a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
					<ul class="dropdown-menu" role="menu">
						<li>
							<a href="{% url 'portal:periodoletivo_new' %}"><strong>INCLUIR</strong></a>
						</li>

					</ul>
				</li>
				<li><a href="#"><i class="fa fa-close"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>


		<div class="x_content">

			<table id="datatable-buttons" class="table table-striped table-bordered">
				<thead>
				<tr>
					<th width="25%">Registro</th>
					<th width="20%">Descrição do Período</th>
					<th width="15%">Dias Letivos</th>
					<th width="20%">Calendário</th>
					<th width="5%"> Ação </th>

				</tr>
				</thead>


				<tbody>
				{% for reg in aluno %}

				"Deu Certo"

				<tr>
					<td>{{ reg.registro_aluno  }}</td>
					<td>{{ reg.nome  }}</td>
					<td>{{ reg.turma  }}</td>
					<td>{{ reg.disciplina  }}</td>
					<td>
						<a href="#">
							<button class="btn btn-success btn-sm"><i class="glyphicon glyphicon-search"></i> Visualizar </button>
						</a>


					</td>

				</tr>
				{% endfor %}
				</tbody>
			</table>


		</div>
	</div>
</div>


{% endblock %}

portal/templates/financeiro.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12 col-sm-12 col-xs-12">
{% for reg1 in responsavel %}
	<div class="x_panel">
		<div class="x_title">
			<h2>{{ reg1.nome }} <small></small></h2>

{% endfor %}
			<ul class="nav navbar-right panel_toolbox">
				<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

				</li>
				<li><a class="close-link"><i class="fa fa-close"></i></a>
				</li>
			</ul>

			<div class="clearfix"></div>
		</div>


		<div class="x_content">

			<table id="datatable-buttons" class="table table-striped table-bordered">
				<thead>
				<tr>
					<th width="10%">Emissão </th>
					<th width="40%">Histórico </th>
					<th width="10%">Vlr. Título </th>
					<th width="3%"> Ação </th>

				</tr>
				</thead>


				<tbody>
				{% for reg in dados %}

				<tr>
					<td>{{ reg.dtemissao|date:'d/m/Y' }}</td>
					<td>{{ reg.historico }}</td>
					<td>{{ reg.vlr_titulo }} </td>
					<td>
						<a href="{% url 'portal:form_aluno' pk=reg.pk %}">
							<button class="btn btn-success btn-sm"><i class="glyphicon glyphicon-search"></i> Visualizar </button>
						</a>


					</td>

				</tr>
				{% endfor %}
				</tbody>
			</table>


		</div>
	</div>

</div>


{% endblock %}

portal/templates/importacao_excel.html
{% extends 'base.html' %}

{% block content %}

<div class="x_panel">
	<div class="x_title">
		<a href="{% url 'portal:importacao_excel' pk=0 %}"><h2>Importação de Dados - Excel <small></small></h2> </a>
		<ul class="nav navbar-right panel_toolbox">
			<li>
				<div class="text-center">
					<a href="{%  url 'portal:upload'  %}" target="_blank">
						<button class="btn btn-success " title="Incluir" ><i class="glyphicon glyphicon-pencil"></i>  </button>
					</a>
				</div>
			</li>

		</ul>
		<div class="clearfix"></div>
	</div>
	{% if importacaoxls %}

	<div class="x_content">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2> Planilhas <small></small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

							</li>
							<li><a class="close-link"><i class="fa fa-close"></i></a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</div>

					<div class="x_content">
						<table id="datatable-buttons" class="table table-striped table-bordered">
							<thead  align="center">
							<tr>

								<th width="40%">Nome da Importação</th>
								<th width="5">Upload</th>
								<th width="5">Importação</th>
								<th width="5%">Status</th>
								<th width="40%">Planilha</th>
								<th width="1%">Ação</th>
							</tr>
							</thead>

							<tbody>
							{% for regimportacaoxls in importacaoxls %}

							<tr>
								<form method="post" enctype="multipart/form-data">
									{% csrf_token %}

									<td> {{ regimportacaoxls.nome_importacao }} </td>
									<td> {{ regimportacaoxls.dtupload|date:'d/m/Y' }}</td>
									<td> {{ regimportacaoxls.dtimportacao|date:'d/m/Y' }}</td>



									<td align="center">

										{% if regimportacaoxls.stimportacao %}

										<i  class="glyphicon glyphicon-ok" title="Importação Concluída"></i>

										{% else %}

										<i  class="glyphicon glyphicon-remove"></i>


    									{% endif %}


									</td>



									<td> <a href="/media/{{ regimportacaoxls.arquivo }}" > {{ regimportacaoxls.arquivo }} </a></td>

									<td>

										{% if not regimportacaoxls.stimportacao %}

										<button type="submit" formaction="{% url 'portal:importacao_excel' pk=regimportacaoxls.pk %}"
												class="btn btn-success btn-sm" title="Importar Dados"
										onclick="return confirm('Importar Dados da Planilha: [{{ regimportacaoxls.arquivo }}] ?')">
											<i class="glyphicon glyphicon-file"></i>  </button>

										{% else %}

										<button type="submit" formaction="{% url 'portal:excluir_dados_importacao' pk=regimportacaoxls.pk %}"
												class="btn btn-danger btn-sm"  title="Excluir - Importação de Dados"
												onclick="return confirm('Excluir Dados da Planilha: [{{ regimportacaoxls.arquivo }}] ?')">
											<i class="glyphicon glyphicon-file"></i> </button>

										{% endif %}

									</td>
								</form>

							</tr>
							{% endfor %}

							</tbody>

						</table>
					</div>



				</div>

			</div>

		</div>
	</div>

	{% else %}

	{% endif %}
	<!-- Mensagens -->

	{% if messages %}

	<div class="x_content">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2> Log de Importação <small></small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

							</li>
							<li><a class="close-link"><i class="fa fa-close"></i></a>
							</li>
						</ul>
						<div class="clearfix"></div>
					</div>

					<div class="x_content">
						{% for message in messages %}
						{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

						<div class="alert alert-danger fade in">
							<button data-dismiss="alert" class="close close-sm" type="button"> &times; </button>
							<strong>ERRO ! {{ message }} {{ erro }} </strong>

						</div>

						{% else %}

						<div class="alert alert-success fade in">
							<button data-dismiss="alert" class="close close-sm" type="button"> &times; </button>
							<strong>CONCLUÍDO ! {{ message }} </strong>


						</div>

						{% endif %}
						{% endfor %}
					</div>

				</div>

			</div>

		</div>
	</div>

	{% endif %}
	<!-- Fim -->

</div>


</div>

<script language="javascript">

function CarregaUF() {

  var selectUF = document.getElementById('uf');

  {% for l_estado in estado %}

    var option = document.createElement('option');
        option.value = ""
        option.value = "{{ l_estado.id }}"
        option.text  = "{{ l_estado.uf }}"

    selectUF.add(option);


  {% endfor %}


}

function CarregaCidade() {

 var select = document.getElementById('uf');

// alert('UF: | ' + $("#uf").val());

 var selectCidade = document.getElementById('cidade');

 $("#cidade").empty();

 {% for l_cidade in cidade %}

 if ($("#uf").val() == {{ l_cidade.estado_id }}) {

    var option = document.createElement('option');
        option.value = "{{ l_cidade.id }}"
        option.text  = "{{ l_cidade.nome }}"

    selectCidade.add(option);

    }

   {% endfor %}

}

</script>

{% endblock %}

portal/templates/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>ABC Mobile</title>

  <!-- Bootstrap core CSS -->

  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

  <link href="{% static "fonts/css/font-awesome.min.css" %}" rel="stylesheet">
  <link href="{% static "css/animate.min.css" %}" rel="stylesheet">

  <!-- Custom styling plus plugins -->
  <link href="{% static "css/custom.css" %}" rel="stylesheet">
  <link href="{% static "css/icheck/flat/green.css" %}" rel="stylesheet">


  <script src="{% static "js/jquery.min.js" %}"></script>

  <!--[if lt IE 9]>
  <script src="../assets/js/ie8-responsive-file-warning.js" %}"></script>
  <![endif]-->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body style="background:#F7F7F7;">
<div id="wrapper">
  <div id="login" class="animate form">

    <section class="login_content">
      <img src="{% static "images/lg_abcmobile.png" %}" />
      <form class="form-signin" action="{% url 'portal:login' %}" method="post">
        {% csrf_token %}
        <h1>Acesso Restrito</h1>
        <div>
          <input type="text" name="username" class="form-control" placeholder="Usuário" required="" />
        </div>
        <div>
          <input type="password" name="password" class="form-control" placeholder="Senha" required="" />
        </div>
        <div>
          <button class="btn btn-default submit" type="submit">Acessar</button>

          <a class="reset_pass" href="#">Relembrar Senha ?</a>
        </div>
        <div class="clearfix"></div>
        <div class="separator">

          <p class="change_link">Novo no Site e
            <a href="{% url 'portal:usuario_new' %}" class="to_register"> Deseja Criar Conta ? </a> <br>
            <!--<a href="#toregister" class="to_register"> Entre em contato conosco </a>-->


          </p>
          <div class="clearfix"></div>
          <br />
          <div>
            <h1><!--i class="fa fa-paw" style="font-size: 26px;"--><!--/i--> ABC MOBILE!</h1>

            <p>©2017 Todos os direitos reservados. ABC Mobile!</p>
          </div>
        </div>
      </form>
      <!-- form -->
    </section>
    <!-- content -->
  </div>
  <div id="register" class="animate form">
    <section class="login_content">
      <form>
        <h1>Create Account</h1>
        <div>
          <input type="text" class="form-control" placeholder="Username" required="" />
        </div>
        <div>
          <input type="email" class="form-control" placeholder="Email" required="" />
        </div>
        <div>
          <input type="password" class="form-control" placeholder="Password" required="" />
        </div>
        <div>
          <a class="btn btn-default submit" href="index.html">Submit</a>
        </div>
        <div class="clearfix"></div>
        <div class="separator">

          <p class="change_link">Already a member ?
            <a href="#tologin" class="to_register"> Log in </a>
          </p>
          <div class="clearfix"></div>
          <br />
          <div>
            <h1><i class="fa fa-paw" style="font-size: 26px;"></i> Gentelella Alela!</h1>

            <p>©2015 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
          </div>
        </div>
      </form>
      <!-- form -->
    </section>
    <!-- content -->
  </div>
</div>

<div class="">
  <!--<a class="hiddenanchor" id="toregister"></a>-->
  <!--<a class="hiddenanchor" id="tologin"></a>-->

</div>

</body>

</html>